[package]
name = "osk-lab"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "osk-lab"
path = "src/main.rs"

[[bin]]
name = "osk-lab-popover"
path = "src/popover_main.rs"

[dependencies]
glib = "0.20"
gtk = { package = "gtk4", version = "0.9", features = ["v4_12"] }
adw = { package = "libadwaita", version = "0.7", features = ["v1_5"] }
